
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test4?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
server:
  port: 8888
  ssl:
    key-store-password: 87pisy3ryy
    key-store-type: JKS
    key-store: classpath:www.csgoha.xyz.jks
